title: Public Feedback for AI Evals
description: Research, practice, & beyond
baseurl: ""
url: "https://jessica-dai.github.io/publicfeedback.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Header links
header_pages:
  - about.md
